sudo: required

services:
  - docker

before_install:
  - docker build -t ajayakce/devops -f Dockerfile.dev .

script:
  - ls
  - $TRAVIS_TEST_RESULT
  - docker run ajayakce/devops npm run test -- --coverage
  - $TRAVIS_TEST_RESULT
